<?php

// Fotografías reales identificadas; créditos Ecuador y licencias abiertos por imagen.
return [
    [
        'kingdom' => 'Animalia',
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Hymenoptera',
        'family' => 'Formicidae',
        'subfamily' => 'Dolichoderinae',
        'genus' => 'Linepithema',
        'species' => 'Linepithema humile',
        'archivo' => 'linepithema-humile',
        'grupo' => 'Formicidae',
        'autor' => '(c) Esteban Poveda, some rights reserved (CC BY)',
        'licencia' => 'CC BY 4.0',
        'licencia_url' => 'https://creativecommons.org/licenses/by/4.0/',
        'fuente' => 'https://www.inaturalist.org/photos/726108359',
        'fuente_taxonomia' => 'https://www.inaturalist.org/taxa/68165',
        'descripcion' => 'Linepithema humile es una hormiga de la familia Formicidae y del género Linepithema. La fotografía corresponde a una observación identificada en Ecuador.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'inaturalist-726108359',
        'credito_ecuador' => true,
        'pais_fotografia' => 'Ecuador',
        'fuente_pais' => 'https://www.inaturalist.org/observations/395977327',
        'lugar_fuente_id' => 7512,
        'subphylum' => 'Hexapoda',
        'subclass' => 'Pterygota',
        'suborder' => 'Apocrita',
        'infraorder' => 'Aculeata',
        'superfamily' => 'Formicoidea',
        'tribe' => 'Leptomyrmecini',
    ],
    [
        'kingdom' => 'Animalia',
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Hymenoptera',
        'family' => 'Formicidae',
        'subfamily' => 'Dolichoderinae',
        'genus' => 'Dolichoderus',
        'species' => 'Dolichoderus bispinosus',
        'archivo' => 'dolichoderus-bispinosus',
        'grupo' => 'Formicidae',
        'autor' => '(c) Fue Her, some rights reserved (CC BY)',
        'licencia' => 'CC BY 4.0',
        'licencia_url' => 'https://creativecommons.org/licenses/by/4.0/',
        'fuente' => 'https://www.inaturalist.org/photos/714222159',
        'fuente_taxonomia' => 'https://www.inaturalist.org/taxa/300626',
        'descripcion' => 'Dolichoderus bispinosus es una hormiga de la familia Formicidae y del género Dolichoderus. La fotografía corresponde a una observación identificada en Ecuador.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'inaturalist-714222159',
        'credito_ecuador' => true,
        'pais_fotografia' => 'Ecuador',
        'fuente_pais' => 'https://www.inaturalist.org/observations/389886151',
        'lugar_fuente_id' => 7512,
        'subphylum' => 'Hexapoda',
        'subclass' => 'Pterygota',
        'suborder' => 'Apocrita',
        'infraorder' => 'Aculeata',
        'superfamily' => 'Formicoidea',
        'tribe' => 'Dolichoderini',
    ],
    [
        'kingdom' => 'Animalia',
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Hymenoptera',
        'family' => 'Formicidae',
        'subfamily' => 'Myrmicinae',
        'genus' => 'Atta',
        'species' => 'Atta cephalotes',
        'archivo' => 'atta-cephalotes',
        'grupo' => 'Formicidae',
        'autor' => '(c) Fue Her, some rights reserved (CC BY)',
        'licencia' => 'CC BY 4.0',
        'licencia_url' => 'https://creativecommons.org/licenses/by/4.0/',
        'fuente' => 'https://www.inaturalist.org/photos/710061977',
        'fuente_taxonomia' => 'https://www.inaturalist.org/taxa/153974',
        'descripcion' => 'Atta cephalotes es una hormiga de la familia Formicidae y del género Atta. La fotografía corresponde a una observación identificada en Ecuador.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'inaturalist-710061977',
        'credito_ecuador' => true,
        'pais_fotografia' => 'Ecuador',
        'fuente_pais' => 'https://www.inaturalist.org/observations/387747121',
        'lugar_fuente_id' => 7512,
        'subphylum' => 'Hexapoda',
        'subclass' => 'Pterygota',
        'suborder' => 'Apocrita',
        'infraorder' => 'Aculeata',
        'superfamily' => 'Formicoidea',
        'tribe' => 'Attini',
        'subtribe' => 'Attina',
    ],
    [
        'kingdom' => 'Animalia',
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Hymenoptera',
        'family' => 'Formicidae',
        'subfamily' => 'Formicinae',
        'genus' => 'Paratrechina',
        'species' => 'Paratrechina longicornis',
        'archivo' => 'paratrechina-longicornis',
        'grupo' => 'Formicidae',
        'autor' => '(c) Slunky, some rights reserved (CC BY)',
        'licencia' => 'CC BY 4.0',
        'licencia_url' => 'https://creativecommons.org/licenses/by/4.0/',
        'fuente' => 'https://www.inaturalist.org/photos/709936107',
        'fuente_taxonomia' => 'https://www.inaturalist.org/taxa/69388',
        'descripcion' => 'Paratrechina longicornis es una hormiga de la familia Formicidae y del género Paratrechina. La fotografía corresponde a una observación identificada en Ecuador.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'inaturalist-709936107',
        'credito_ecuador' => true,
        'pais_fotografia' => 'Ecuador',
        'fuente_pais' => 'https://www.inaturalist.org/observations/387685108',
        'lugar_fuente_id' => 7512,
        'subphylum' => 'Hexapoda',
        'subclass' => 'Pterygota',
        'suborder' => 'Apocrita',
        'infraorder' => 'Aculeata',
        'superfamily' => 'Formicoidea',
        'tribe' => 'Lasiini',
    ],
    [
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Orthoptera',
        'family' => 'Acrididae',
        'genus' => 'Locusta',
        'species' => 'Locusta migratoria',
        'kingdom' => 'Animalia',
        'archivo' => 'locusta-migratoria',
        'grupo' => 'Orthoptera',
        'autor' => '',
        'licencia' => 'Dominio público (PD-self / PD-user)',
        'licencia_url' => 'https://commons.wikimedia.org/wiki/Template:PD-self',
        'fuente' => 'https://commons.wikimedia.org/wiki/File:Locusta_migratoria.jpg',
        'fuente_taxonomia' => 'https://www.gbif.org/species/233223736',
        'descripcion' => 'Locusta migratoria pertenece a la familia Acrididae y al género Locusta. La fotografía muestra un organismo identificado de este grupo de invertebrados.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'commons-locusta-migratoria',
        'credito_ecuador' => false,
        'pais_fotografia' => '',
    ],
    [
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Phasmatodea',
        'family' => 'Phasmatidae',
        'genus' => 'Extatosoma',
        'species' => 'Extatosoma tiaratum',
        'kingdom' => 'Animalia',
        'archivo' => 'extatosoma-tiaratum',
        'grupo' => 'Phasmatodea',
        'autor' => '',
        'licencia' => 'Dominio público (PD-self)',
        'licencia_url' => 'https://commons.wikimedia.org/wiki/Template:PD-self',
        'fuente' => 'https://commons.wikimedia.org/wiki/File:Extatosoma_tiaratum.jpg',
        'fuente_taxonomia' => 'https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=614105',
        'descripcion' => 'Extatosoma tiaratum pertenece a la familia Phasmatidae y al género Extatosoma. La fotografía muestra un organismo identificado de este grupo de invertebrados.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'commons-extatosoma-tiaratum',
        'credito_ecuador' => false,
        'pais_fotografia' => '',
    ],
    [
        'phylum' => 'Arthropoda',
        'class' => 'Insecta',
        'order' => 'Hemiptera',
        'family' => 'Pentatomidae',
        'genus' => 'Graphosoma',
        'species' => 'Graphosoma italicum',
        'kingdom' => 'Animalia',
        'archivo' => 'graphosoma-italicum',
        'grupo' => 'Hemiptera',
        'autor' => '',
        'licencia' => 'Dominio público (PD-user-w)',
        'licencia_url' => 'https://commons.wikimedia.org/wiki/Template:PD-user-w',
        'fuente' => 'https://commons.wikimedia.org/wiki/File:Graphosoma_italicum.jpg',
        'fuente_taxonomia' => 'https://www.gbif.org/species/7437802',
        'descripcion' => 'Graphosoma italicum pertenece a la familia Pentatomidae y al género Graphosoma. La fotografía muestra un organismo identificado de este grupo de invertebrados.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'commons-graphosoma-italicum',
        'credito_ecuador' => false,
        'pais_fotografia' => '',
    ],
    [
        'phylum' => 'Mollusca',
        'class' => 'Gastropoda',
        'order' => 'Stylommatophora',
        'family' => 'Helicidae',
        'genus' => 'Cornu',
        'species' => 'Cornu aspersum',
        'kingdom' => 'Animalia',
        'archivo' => 'cornu-aspersum',
        'grupo' => 'Gastropoda',
        'autor' => '',
        'licencia' => 'CC0 1.0',
        'licencia_url' => 'https://creativecommons.org/publicdomain/zero/1.0/',
        'fuente' => 'https://commons.wikimedia.org/wiki/File:Cornu_aspersum.jpg',
        'fuente_taxonomia' => 'https://www.gbif.org/species/8539436',
        'descripcion' => 'Cornu aspersum pertenece a la familia Helicidae y al género Cornu. La fotografía muestra un organismo identificado de este grupo de invertebrados.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'commons-cornu-aspersum',
        'credito_ecuador' => false,
        'pais_fotografia' => '',
    ],
    [
        'phylum' => 'Nematoda',
        'class' => 'Chromadorea',
        'order' => 'Rhabditida',
        'family' => 'Rhabditidae',
        'genus' => 'Caenorhabditis',
        'species' => 'Caenorhabditis elegans',
        'kingdom' => 'Animalia',
        'archivo' => 'caenorhabditis-elegans',
        'grupo' => 'Nematoda',
        'autor' => '',
        'licencia' => 'Dominio público (PD-USGov-NIH)',
        'licencia_url' => 'https://commons.wikimedia.org/wiki/Template:PD-USGov-NIH',
        'fuente' => 'https://commons.wikimedia.org/wiki/File:Caenorhabditis_elegans.jpg',
        'fuente_taxonomia' => 'https://www.gbif.org/species/2283683',
        'descripcion' => 'Caenorhabditis elegans pertenece a la familia Rhabditidae y al género Caenorhabditis. La fotografía muestra un organismo identificado de este grupo de invertebrados.',
        'cambios' => 'Reducción a un máximo de 320 px y conversión a WebP.',
        'id' => 'commons-caenorhabditis-elegans',
        'credito_ecuador' => false,
        'pais_fotografia' => '',
    ],
];
