<?php

return [
    'mapa' => ['numero' => 1, 'texto' => 'El mapa muestra dónde se recolectaron los registros públicos que cumplen los filtros actuales. Cada punto conserva las coordenadas originales de una ubicación. Al alejarte, las ubicaciones cercanas se agrupan; al acercarte, vuelven a separarse. El tamaño expresa cantidad de registros y el color distingue los filos presentes. Selecciona una ubicación para explorar su clasificación y sus ejemplares. Estos datos describen material documentado por la colección; no indican cuántos animales viven actualmente en ese lugar ni representan un censo ambiental.'],
    'filos' => ['numero' => 2, 'texto' => 'Este panel compara cuántos registros publicados pertenecen a cada filo, un grupo amplio de animales con características compartidas. Los colores coinciden con los del mapa y los porcentajes se calculan sobre la selección actual. Un filo puede reunir clases, familias y especies diferentes. Selecciona uno o varios para estudiar su distribución y combinar esa elección con los filtros geográficos. Una proporción grande indica mayor representación en el catálogo consultado; no demuestra que ese grupo sea más abundante en la naturaleza.'],
    'riqueza' => ['numero' => 3, 'texto' => 'Aquí aparecen las diez provincias con más registros públicos dentro de la selección aplicada. Cada valor cuenta entradas del catálogo, aunque varias correspondan a una misma especie o colecta. La comparación ayuda a reconocer dónde existe más material documentado para consultar. Seleccionar una provincia actualiza el mapa y los demás paneles, manteniendo los otros criterios. Las provincias con pocos registros pueden haber recibido menos muestreo o digitalización. Por eso, esta figura no permite concluir cuál provincia tiene mayor biodiversidad natural.'],
    'decadas' => ['numero' => 4, 'texto' => 'La cobertura temporal muestra cómo se distribuyen los registros según la década de su fecha inicial de colecta. La línea permite reconocer periodos con mayor documentación y cambios entre épocas, respetando la distancia temporal entre décadas. Seleccionar un punto aplica ese periodo a toda la vista. Se utilizan únicamente fechas públicas válidas; las fechas pendientes de revisión quedan fuera. Un aumento puede reflejar campañas de colecta, digitalización o publicación de material, sin demostrar cambios en las poblaciones naturales de animales.'],
    'estacionalidad' => ['numero' => 5, 'texto' => 'Las columnas comparan los registros de cada mes, reuniendo todos los años incluidos en los filtros. El orden de enero a diciembre facilita reconocer cuándo se concentraron las colectas documentadas. Seleccionar un mes conserva los años y los demás criterios de la consulta. Solo participan registros con fechas públicas válidas. Una columna baja puede deberse a menor esfuerzo de muestreo, material sin fecha o información no publicada. Esta figura describe el calendario de documentación, sin medir actividad biológica ni abundancia.'],
    'altitud' => ['numero' => 6, 'texto' => 'Los puntos comparan la cantidad de registros cuyos valores públicos de elevación coinciden con cada intervalo mostrado. Esta presentación facilita reconocer franjas con más material documentado, sin sugerir que todas tienen la misma amplitud. Seleccionar una franja filtra la colección por solapamiento de elevaciones. Si una colecta abarca varias franjas, puede aparecer en más de una; los conteos no deben sumarse. Los registros sin elevación pública quedan fuera. La figura ayuda a explorar cobertura del muestreo, sin medir preferencias ambientales.'],
    'metodos' => ['numero' => 7, 'texto' => 'Este panel organiza los registros por la técnica utilizada para recolectar el material. Las categorías reúnen variantes de escritura del mismo método, mientras las fichas conservan su valor original. Seleccionar una técnica permite revisar dónde y cuándo se obtuvo ese material, manteniendo los otros filtros. Los conteos ayudan a identificar series comparables y métodos mejor documentados. Sin información sobre duración, número de trampas o esfuerzo de campo, una categoría grande no demuestra mayor eficacia de captura ni abundancia de animales.'],
];
